spring.application.name=stock-service
server.port=8082

# Alamat Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Opsional: Agar lebih cepat terdeteksi saat pengembangan
eureka.instance.lease-renewal-interval-in-seconds=5

# URL Database H2 (disimpan di memori, hilang saat restart)
spring.datasource.url=jdbc:h2:mem:stockdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Agar kita bisa melihat isi database via browser di localhost:port/h2-console
spring.h2.console.enabled=true

# Biarkan Hibernate membuat tabel otomatis berdasarkan @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true